# Generated by Django 5.0.6 on 2024-05-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentForm',
            new_name='Student',
        ),
    ]
