# Generated by Django 5.0.6 on 2024-05-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_studentform_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Contact',
            field=models.CharField(max_length=10),
        ),
    ]
